# Configurations
title:            RB3 on PC
longtitle:        Rock Band 3 on PC with RPCS3
author:           Carl Mylo for Milohax
email:            carl@carlmylo.com
description: >
  How to set up Rock Band 3 to run on a computer with RPCS3.

version:          1.0
gitbook_version:  3.2.3

url:              'https://carlmylo.github.io'
baseurl:          '/rpcs3guidetesting'
rss:              RSS

languages: ["en", "es"]
default_lang: "en"
exclude_from_localization: ["javascript", "images", "css", "public", "customconfig", "instrument-repo"]
parallel_localization: true

# bootstrap: use the remote theme for the site itself
remote_theme: sighingnow/jekyll-gitbook

toc:
  enabled: true
  h_min: 1
  h_max: 3

# customize the link favicon in header, will be {{site.baseurl}}/{{site.favicon_path}}
favicon_path:     /assets/gitbook/images/favicon.ico

# markdown render engine.
markdown:         kramdown
kramdown:
  auto_ids:               true
  input:                  GFM
  math_engine:            mathjax
  smart_quotes:           lsquo,rsquo,ldquo,rdquo
  toc_levels:             1..6
  syntax_highlighter:     rouge
  syntax_highlighter_opts:
    guess_lang:           true

syntax_highlighter_style: colorful

markdown_ext:             markdown,mkdown,mkdn,mkd,md

# Permalinks
permalink:                /:categories/:year-:month-:day-:title:output_ext

# Disqus comments
# disqushandler:            sighingnow

exclude:
  - _drafts

collections:
  pages:
    output: true
    permalink: /:collection/:path/

  english:
    output: true
    permalink: /:collection/:path/

  espanol:
    output: true
    permalink: /:collection/:path/

  instruments:
    output: true
    permalink: /:collection/:path/


page_width: 800px

destination:      ./_site
incremental:      false
regenerate:       true

plugins:
  - jekyll-feed
  - jekyll-readme-index
  - jemoji
  - jekyll-polyglot